version: "2"
services:
  build-test:
    image: node:16
    command: /bin/bash ./ops/ci/build_test.sh
    volumes:
      - .:/root/app
    working_dir: /root/app
    environment:
      - YARN_CACHE_FOLDER=/yarn_home/.cache
      - NPM_TOKEN
  build-publish:
    image: node:16
    command: /bin/bash ./ops/ci/publish.sh
    volumes:
      - .:/root/app
    working_dir: /root/app
    environment:
      - YARN_CACHE_FOLDER=/yarn_home/.cache
      - NPM_TOKEN
      - GITHUB_USER_EMAIL
      - GITHUB_USER_NAME
      - GITHUB_TOKEN
      - BUILDKITE_REPO
